rm -rf ./../archives.html
rm -rf ./../author
rm -rf ./../authors.html
rm -rf ./../categories.html
rm -rf ./../category
rm -rf ./../czhong-lei-cheng-yuan-bian-liang-de-chu-shi-hua.html
rm -rf ./../index.html
rm -rf ./../my-super-post.html
rm -rf ./../pelicanan-zhuang-guo-cheng.html
rm -rf ./../tag
rm -rf ./../tags.html
rm -rf ./../theme
rm -rf ./../wen-zhang-biao-ti.html
